/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProductManagement;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.List;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;


import model.ProductManagement.Product;
import model.Supplier.Supplier;
import model.Supplier.SupplierDirectory;


import model.ProductManagement.*;
import model.Supplier.Supplier;
import javax.swing.*;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author vartika
 */
public class ProductManagementJPanel extends javax.swing.JPanel {

    private Supplier supplier;
    private JTable tableProduct;

    public ProductManagementJPanel(Supplier supplier) {
        this.supplier = supplier;
        initComponents();
        populateTable();
    }

    private void initComponents() {
        setLayout(new BorderLayout());

        JButton btnBrowsePerformance = new JButton("Browse Product Performance");
        JButton btnAdjustPrices = new JButton("Adjust Prices");

        JPanel buttonPanel = new JPanel();
        buttonPanel.add(btnBrowsePerformance);
        buttonPanel.add(btnAdjustPrices);
        add(buttonPanel, BorderLayout.NORTH);

        tableProduct = new JTable();
        JScrollPane scrollPane = new JScrollPane(tableProduct);
        add(scrollPane, BorderLayout.CENTER);

        btnBrowsePerformance.addActionListener(e -> analyzeProductPerformance());
        btnAdjustPrices.addActionListener(e -> adjustProductPrices());
    }

    private void populateTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"Product", "Floor Price", "Ceiling Price", "Target Price"});
        for (Product product : supplier.getProductCatalog().getProducts()) {
            model.addRow(new Object[]{product.getName(), product.getFloorPrice(), product.getCeilingPrice(), product.getTargetPrice()});
        }
        tableProduct.setModel(model);
    }

    private void analyzeProductPerformance() {
        JOptionPane.showMessageDialog(this, "Analyzing product performance...");
    }

    private void adjustProductPrices() {
        for (Product product : supplier.getProductCatalog().getProducts()) {
            if (product.getSalesVolume() < product.getTargetPrice()) {
                product.adjustTargetPrice(false); // Decrease target price
            } else {
                product.adjustTargetPrice(true); // Increase target price
            }
        }
        populateTable();
    }


    /**
     * Creates new form ProductManagementJPanel
     */



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();

        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Supplier", "Product Name", "Floor Price", "Ceiling Price", "Target Price"
            }
        ));
        jScrollPane1.setViewportView(tableProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProduct;
    // End of variables declaration//GEN-END:variables
}
