/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ProductManagement;

import java.awt.CardLayout;
import java.awt.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.ProductManagement.Product;
import model.Supplier.Supplier;
import model.Supplier.SupplierDirectory;

/**
 *
 * @author vartika
 */
public class ProductManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductManagementJPanel
     */
     JPanel userProcessContainer;
    SupplierDirectory supplierDirectory;

    public ProductManagementJPanel(JPanel container, SupplierDirectory directory) {
       // Set a layout if needed
        initComponents();
         
        userProcessContainer = container;
        supplierDirectory = directory;
        
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduct = new javax.swing.JTable();

        tableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Supplier", "Product Name", "Floor Price", "Ceiling Price", "Target Price"
            }
        ));
        jScrollPane1.setViewportView(tableProduct);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) tableProduct.getModel();
    model.setRowCount(0); // Clear existing rows if any

    // Populate the table with supplier and product data
    for (Supplier supplier : supplierDirectory.getSuplierList()) {
        for (Product product : supplier.getProductCatalog().getProducts()) {
            Object[] row = new Object[5];
            row[0] = supplier.getName(); // Supplier name
            row[1] = product; // Assuming Product overrides toString() to show product name
            row[2] = product.getFloorPrice(); // Floor Price
            row[3] = product.getCeilingPrice(); // Ceiling Price
            row[4] = product.getTargetPrice(); // Target Price

            model.addRow(row);
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProduct;
    // End of variables declaration//GEN-END:variables

}
