/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
import model.Supplier.Supplier;
import model.Supplier.SupplierDirectory;

/**
 *
 * @author vartika
 */


public class LoginScreenJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreenJPanel
     */
    
    JPanel userProcessContainer;
    SupplierDirectory supplierDirectory;
    Supplier selectedSupplier = null;

    public LoginScreenJPanel(JPanel userProcessContainer, SupplierDirectory supplierDirectory) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.supplierDirectory = supplierDirectory;
          populateDemoData();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSupplier = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        cmbSuppliers = new javax.swing.JComboBox<>();

        lblSupplier.setText("Select Supplier:");

        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        cmbSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSuppliersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(115, 115, 115)
                    .addComponent(lblSupplier)
                    .addGap(32, 32, 32)
                    .addComponent(cmbSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(411, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSupplier))
                    .addContainerGap(299, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
       
    }//GEN-LAST:event_btnLogInActionPerformed

    private void cmbSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSuppliersActionPerformed
        // TODO add your handling code here:
        // Check if the selected item is null
         selectedSupplier = (Supplier) cmbSuppliers.getSelectedItem();
    if (selectedSupplier != null) {
        // Display or process information related to the selected supplier
        System.out.println("Selected Supplier: " + selectedSupplier.getName());
        
    }
       
    }//GEN-LAST:event_cmbSuppliersActionPerformed

private void populateDemoData() {
    // Assuming supplierDirectory is already defined in the scope and initialized

    Supplier bestBuy = supplierDirectory.newSupplier("Best Buy");
    System.out.println("Created Supplier: " + bestBuy.getName());

    // Add products to bestBuy
    bestBuy.getProductCatalog().newProduct("TV", 100, 500, 400);
    System.out.println("Added Product to " + bestBuy.getName() + ": TV, Target Price: 400, Floor Price: 100, Ceiling Price: 500");

    bestBuy.getProductCatalog().newProduct("Laptop", 300, 1200, 800);
    System.out.println("Added Product to " + bestBuy.getName() + ": Laptop, Target Price: 800, Floor Price: 300, Ceiling Price: 1200");

    Supplier supplier1 = supplierDirectory.newSupplier("Best Electronics");
    System.out.println("Created Supplier: " + supplier1.getName());

    // Add products to supplier1
    supplier1.getProductCatalog().newProduct("Smartphone", 200, 700, 600);
    System.out.println("Added Product to " + supplier1.getName() + ": Smartphone, Target Price: 600, Floor Price: 200, Ceiling Price: 700");

    supplier1.getProductCatalog().newProduct("Headphones", 20, 200, 100);
    System.out.println("Added Product to " + supplier1.getName() + ": Headphones, Target Price: 100, Floor Price: 20, Ceiling Price: 200");

    Supplier supplier2 = supplierDirectory.newSupplier("Tech Gadgets");
    System.out.println("Created Supplier: " + supplier2.getName());

    // Add products to supplier2
    supplier2.getProductCatalog().newProduct("Tablet", 150, 800, 500);
    System.out.println("Added Product to " + supplier2.getName() + ": Tablet, Target Price: 500, Floor Price: 150, Ceiling Price: 800");

    supplier2.getProductCatalog().newProduct("Smartwatch", 50, 300, 250);
    System.out.println("Added Product to " + supplier2.getName() + ": Smartwatch, Target Price: 250, Floor Price: 50, Ceiling Price: 300");

    Supplier supplier3 = supplierDirectory.newSupplier("Home Appliances");
    System.out.println("Created Supplier: " + supplier3.getName());

    // Add products to supplier3
    supplier3.getProductCatalog().newProduct("Refrigerator", 500, 1500, 1000);
    System.out.println("Added Product to " + supplier3.getName() + ": Refrigerator, Target Price: 1000, Floor Price: 500, Ceiling Price: 1500");

    supplier3.getProductCatalog().newProduct("Microwave", 100, 400, 300);
    System.out.println("Added Product to " + supplier3.getName() + ": Microwave, Target Price: 300, Floor Price: 100, Ceiling Price: 400");
    
    
       // Populate the combo box with suppliers
    cmbSuppliers.removeAllItems(); // Clear existing items
    for (Supplier supplier : supplierDirectory.getSuplierList()) {
        cmbSuppliers.addItem(supplier);
    }
}




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JComboBox<Supplier> cmbSuppliers;
    private javax.swing.JLabel lblSupplier;
    // End of variables declaration//GEN-END:variables
}
